version: '3'
services:
    readthedocs:
        container_name: helpcenter-readthedocs
        build: ./readthedocs
        command: /usr/local/bin/uwsgi /var/readthedocs/readthedocs.ini
        volumes:
            - readthedocs:/var/readthedocs
        environment:
            DEBUG: 'True'
            EMAIL_HOST: 'docs.example.com'
            EMAIL_PORT: 25
            EMAIL_HOST_USER: 'no-reply@example.com'
            EMAIL_HOST_PASSWORD: '123456'
            DEFAULT_FROM_EMAIL: 'no-reply@example.com'

    nginx:
        image: nginx
        container_name: helpcenter-nginx
        links:
            - readthedocs:readthedocs
        ports:
            - 80:80
        volumes:
            - readthedocs:/var/readthedocs:ro
            - ./nginx/readthedocs.conf:/etc/nginx/conf.d/default.conf
volumes:
    readthedocs: