---
version: '3.2'
services:
    readthedocs:
        container_name: x-readthedocs
        build: ./readthedocs
        command: /usr/local/bin/uwsgi /var/readthedocs/readthedocs.ini
        volumes:
            - readthedocs:/var/readthedocs
        environment:
            PRODUCTION_DOMAIN: ${PRODUCTION_DOMAIN}
            TIME_ZONE: ${TIME_ZONE}
            EMAIL_HOST: ${EMAIL_HOST}
            EMAIL_PORT: ${EMAIL_PORT}
            EMAIL_HOST_USER: ${EMAIL_HOST_USER}
            EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
            DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
            ALLOW_ADMIN: ${ALLOW_ADMIN}
            DEBUG: ${DEBUG}
    nginx:
        image: nginx
        container_name: x-nginx
        links:
            - readthedocs:readthedocs
        ports:
            - 80:80
        volumes:
            - readthedocs:/var/readthedocs:ro
            - ./nginx/readthedocs.conf:/etc/nginx/conf.d/default.conf
volumes:
    readthedocs:
