version: '3'
services:
    readthedocs:
        container_name: helpcenter-readthedocs
        build: ./readthedocs
        command: /usr/local/bin/uwsgi /var/readthedocs/readthedocs.ini
        volumes:
            - readthedocs:/var/readthedocs
        environment:
            DEBUG: ${RTD_DEBUG}
            EMAIL_HOST: ${RTD_EMAIL_HOST}
            EMAIL_PORT: ${RTD_EMAIL_PORT}
            EMAIL_HOST_USER: ${RTD_EMAIL_HOST_USER}
            EMAIL_HOST_PASSWORD: ${RTD_EMAIL_HOST_PASSWORD}
            DEFAULT_FROM_EMAIL: ${RTD_DEFAULT_FROM_EMAIL}

    nginx:
        image: nginx
        container_name: helpcenter-nginx
        links:
            - readthedocs:readthedocs
        ports:
            - 80:80
        volumes:
            - readthedocs:/var/readthedocs:ro
            - ./nginx/readthedocs.conf:/etc/nginx/conf.d/default.conf
volumes:
    readthedocs: